### ISSUE TITLE
Se debe recuperar una lista ordenada de las claves 

### ISSUE THREAD

**Issue by evolentini** [carlosdomenje/tdd_tp2_cdomenje#1]
El requisito es que se puede obtener un vector ordenado con todas las claves almacenadas en la lista, y sin el valor. Las pruebas apuntaban a tomar una lista con elementos (como vos hiciste) agregar un elemento con una clave menor a la primera clave existente y que al pedir la lista de claves la misma esté ordenada. Y lo mismo pero con una clave mayor a la ultima existente.

https://github.com/carlosdomenje/tdd_tp2_cdomenje/blob/6d76b802ba602b881e37a41c1eadc6924e19f553/test/test_lista.js#L70-L76

**Comment by carlosdomenje** [comment]
> El requisito es que se puede obtener un vector ordenado con todas las claves almacenadas en la lista, y sin el valor. Las pruebas apuntaban a tomar una lista con elementos (como vos hiciste) agregar un elemento con una clave menor a la primera clave existente y que al pedir la lista de claves la misma esté ordenada. Y lo mismo pero con una clave mayor a la ultima existente.
> 
> https://github.com/carlosdomenje/tdd_tp2_cdomenje/blob/6d76b802ba602b881e37a41c1eadc6924e19f553/test/test_lista.js#L70-L76

Perfecto Esteban, comprendi mal la consigna. Lo modifique siguiendo tus sugerencias. Quedo atento a tus comentarios si esta bien la resolucion.
