### ISSUE TITLE
Se debe mejorar la prueba

### ISSUE THREAD

**Issue by evolentini** [carlosdomenje/tdd_tp2_cdomenje#2]
Usar solo el valor de retorno de la función no es una buena prueba de que se borró un elemento. Sería mejor buscar la clave y obtener una NaN como valor o revisar la cantidad de elementos antes y despues del borrado, o ambas cosas como dos pruebas independientes.

https://github.com/carlosdomenje/tdd_tp2_cdomenje/blob/6d76b802ba602b881e37a41c1eadc6924e19f553/test/test_lista.js#L116-L118

**Comment by carlosdomenje** [comment]
> Usar solo el valor de retorno de la función no es una buena prueba de que se borró un elemento. Sería mejor buscar la clave y obtener una NaN como valor o revisar la cantidad de elementos antes y despues del borrado, o ambas cosas como dos pruebas independientes.
> 
> https://github.com/carlosdomenje/tdd_tp2_cdomenje/blob/6d76b802ba602b881e37a41c1eadc6924e19f553/test/test_lista.js#L116-L118

Entiendo el error, modifique el return realizando una busqueda de la clave que previamente elimine.
