### ISSUE TITLE
Solo se recupera la lista de claves ordenada

### ISSUE THREAD

**Issue by evolentini** [carlosdomenje/tdd_tp2_cdomenje#3]
No era un requisito que se recupere toda la lista ordenada, solo las claves.

https://github.com/carlosdomenje/tdd_tp2_cdomenje/blob/6d76b802ba602b881e37a41c1eadc6924e19f553/test/test_lista.js#L97-L102

**Comment by carlosdomenje** [comment]
> No era un requisito que se recupere toda la lista ordenada, solo las claves.
> 
> https://github.com/carlosdomenje/tdd_tp2_cdomenje/blob/6d76b802ba602b881e37a41c1eadc6924e19f553/test/test_lista.js#L97-L102

La funcion implementada devuelve solo las claves. la funcion sortedList() solamente esta copiando dentro del bucle for las claves del elemento y eso es lo que esta retornando. La prueba pasa porque la compara con el orderedList que es la lista de claves ordenadas. Mas alla de eso, agregue algunos comentarios a la funcion.
