### ISSUE TITLE
Las pruebas deben ser independientes

### ISSUE THREAD

**Issue by evolentini** [carlosdomenje/tdd_tp2_cdomenje#5]
Las pruebas (los it's ) se deben poder ejecutar individualmente  y en cualquier orden, y en estos caos eso no sucede.

https://github.com/carlosdomenje/tdd_tp2_cdomenje/blob/2110bdf1292b2b9c8bb22c0e870f90a99fcbe6ed/test/test_lista.js#L63-L112

**Comment by carlosdomenje** [comment]
> Las pruebas (los it's ) se deben poder ejecutar individualmente y en cualquier orden, y en estos caos eso no sucede.
> 
> https://github.com/carlosdomenje/tdd_tp2_cdomenje/blob/2110bdf1292b2b9c8bb22c0e870f90a99fcbe6ed/test/test_lista.js#L63-L112

En el caso de las listas con claves ordenadas al principio y al final, solo se deja una función que devuelve las claves ordenadas. En las pruebas se puede ver que se pueden agregar en cualquier posición y el resultado es una lista de claves ordenadas alfabéticamente. No tiene sentido dejar dos funciones que realizan la misma tarea, por lo que opte por dejar una funcion que devuelve claves ordenadas. 

En el caso de la ejecución del orden de las pruebas se verificaron las mismas según las sugerencias cambiando su orden y ejecutando el test.

**Comment by evolentini** [comment]
Correcto
